sudo: required
dist: xenial
language: python
virtualenv:
  system_site_packages: true
python:
- '3.5'
install:
- pip install -r requirements.txt
jobs:
  include:
  - stage: test
    script: pytest
    after_script: cd ~
  - stage: deploy-test
    if: branch = test
    name: Deploy to Test PyPi
    script: skip
    deploy:
      on:
        branch: test
        condition: "$TRAVIS_BRANCH = test"
      provider: pypi
      twine_version: 1.12.1
      server: https://test.pypi.org/legacy/
      user: TaylorFacen
      password:
        secure: EoXfuRqKJ1BmBYV2K8LvffMNReHVb3frwxhmuysm7rsm1iBxL4LqLQEtvPP6OhwYY3IE7AEUn5K91jLkoDhTYIWK5OqPMr2D2lCkI9NSbQyItmpM5iIMwgh0CTQOshsk58xMEjN+YSsbSNc9E8f2zGdjv6W+hLZFP0rqUboOge6Vb0Eg6HG+Y5+U6H9tGOCA+FZXYJ37WmxJKtfEy1kunLlh6XbqOES0hQ6y86DWH61Q/IBdmj/hHKV35pWhN9IzfmSTBuICUHY3ciFNMtZ8q1iPy8JSwZNfW+lWnN1NKR2bgSk3Fv4D6CGBpNgjAVAc6zjsL4VJadjNA7Mff2nlqxYbQp11DSopU4fVjNRb/Uxu6QDIS8VqRbJfHF2GlZqthWUghOF7WNeHKCc2SpLDhmZgoYEdGWBcErlGksHgKKg70YMFhYNJgUafq6ni6/38aD4tgJLDUYNiHkwSZpWmPZbNP4GExQEhPqGpTSyd5zPHwpvNvzHm1azfE4qM4DC51L2SLsDSCsPdJt8Pxcoc3brfgJzC/B5QgvkAlY7nO+udNHTixbQDzUxpqqzV73qZKHUxQI++FjSNNHtcdVabS1nSduG809RBCopz/ORcMC4jq5V/EZ9NRFDASnpicXK1mI0XV4uSAIiQRRl5XDzLFUs2SH/vS0JhVPI/VE87xzU=
  - stage: deploy-production
    if: branch = master
    name: Deploy to PyPi
    script: skip
    deploy:
      on:
        branch: master
        condition: "$TRAVIS_BRANCH = master"
      provider: pypi
      twine_version: 1.12.1
      user: TaylorFacen
      password:
        secure: EoXfuRqKJ1BmBYV2K8LvffMNReHVb3frwxhmuysm7rsm1iBxL4LqLQEtvPP6OhwYY3IE7AEUn5K91jLkoDhTYIWK5OqPMr2D2lCkI9NSbQyItmpM5iIMwgh0CTQOshsk58xMEjN+YSsbSNc9E8f2zGdjv6W+hLZFP0rqUboOge6Vb0Eg6HG+Y5+U6H9tGOCA+FZXYJ37WmxJKtfEy1kunLlh6XbqOES0hQ6y86DWH61Q/IBdmj/hHKV35pWhN9IzfmSTBuICUHY3ciFNMtZ8q1iPy8JSwZNfW+lWnN1NKR2bgSk3Fv4D6CGBpNgjAVAc6zjsL4VJadjNA7Mff2nlqxYbQp11DSopU4fVjNRb/Uxu6QDIS8VqRbJfHF2GlZqthWUghOF7WNeHKCc2SpLDhmZgoYEdGWBcErlGksHgKKg70YMFhYNJgUafq6ni6/38aD4tgJLDUYNiHkwSZpWmPZbNP4GExQEhPqGpTSyd5zPHwpvNvzHm1azfE4qM4DC51L2SLsDSCsPdJt8Pxcoc3brfgJzC/B5QgvkAlY7nO+udNHTixbQDzUxpqqzV73qZKHUxQI++FjSNNHtcdVabS1nSduG809RBCopz/ORcMC4jq5V/EZ9NRFDASnpicXK1mI0XV4uSAIiQRRl5XDzLFUs2SH/vS0JhVPI/VE87xzU=
